/*
	Nama	: Horas Marolop Amsal Siregar
	NIM		: 11321051
	Kelas	: 32TI2
*/

-- Task:
-- 1. Create view for each task from : W06S02 Query Multiple Table
-- You must try to select the view to display the result set.

CREATE VIEW PLAYERS_WITHOUT_MATCHES
AS
    SELECT P.PLAYERNO, P.NAME
    FROM PLAYERS P
        LEFT OUTER JOIN MATCHES M ON P.PLAYERNO = M.PLAYERNO
    WHERE M.PLAYERNO IS NULL

CREATE VIEW PLAYER_TOTAL_PENALTIES
AS
    SELECT P.PLAYERNO, P.NAME, SUM(PE.AMOUNT) AS TOTAL_AMOUNT
    FROM PLAYERS P
        INNER JOIN PENALTIES PE ON P.PLAYERNO = PE.PLAYERNO
    GROUP BY P.PLAYERNO, P.NAME

CREATE VIEW PLAYER_TOTAL_PENALTIES_FROM_INGLEWOOD
AS
    SELECT SUM(PE.AMOUNT) AS TOTAL_AMOUNT
    FROM PLAYERS P
        INNER JOIN PENALTIES PE ON P.PLAYERNO = PE.PLAYERNO
    WHERE P.TOWN = 'Inglewood'

CREATE VIEW PLAYER_TOTAL_PENALTIES_HIGHER_THAN_100
AS
    SELECT P.PLAYERNO, P.NAME
    FROM PLAYERS P
        INNER JOIN PENALTIES PE ON P.PLAYERNO = PE.PLAYERNO
    GROUP BY P.PLAYERNO, P.NAME
    HAVING SUM(PE.AMOUNT) > 100

CREATE VIEW TEAM_TOTAL_SET_WON
AS
    SELECT T.TEAMNO, M.MATCHNO, SUM(M.WON) AS TOTAL_SET
    FROM TEAMS T
        INNER JOIN MATCHES M ON T.TEAMNO = M.TEAMNO
    WHERE T.DIVISION = 'First'
    GROUP BY T.TEAMNO, M.MATCHNO

CREATE VIEW PLAYER_TOTAL_PENALTIES_MORE_THAN_ONE
AS
    SELECT P.NAME, P.INITIALS, COUNT(PE.PAYMENTNO) AS TOTAL_PENALTY
    FROM PLAYERS P
        INNER JOIN PENALTIES PE ON P.PLAYERNO = PE.PLAYERNO
    GROUP BY P.NAME, P.INITIALS
    HAVING COUNT(PE.PAYMENTNO) > 1
    ORDER BY P.INITIALS

CREATE VIEW PLAYER_TOTAL_PENALTIES_MORE_THAN_40
AS
    SELECT P.NAME, P.INITIALS, COUNT(PE.PAYMENTNO) AS TOTAL_PENALTIES, AMOUNT
    FROM PLAYERS P
        INNER JOIN PENALTIES PE ON P.PLAYERNO = PE.PLAYERNO
    GROUP BY P.NAME, P.INITIALS, PE.AMOUNT
    HAVING PE.AMOUNT > 40

CREATE VIEW PLAYER_TOWN
AS
    SELECT TOWN, COUNT(PLAYERNO) AS AVG
    FROM PLAYERS
    GROUP BY TOWN

CREATE VIEW PENALTIES_DIFFERENCE
AS
    SELECT PAYMENTNO, AMOUNT, ABS(AMOUNT - (SELECT AVG(AMOUNT)
        FROM PENALTIES)) AS Difference
    FROM PENALTIES

CREATE VIEW TEAM_PLAYERS_WON_MATCHES
AS
    SELECT T.TEAMNO, COUNT(M.PLAYERNO) AS NUM_OF_PLAYERS
    FROM TEAMS T
        INNER JOIN MATCHES M ON T.TEAMNO = M.TEAMNO
    WHERE M.PLAYERNO IN (SELECT PLAYERNO
    FROM PLAYERS P
    WHERE P.TOWN = 'Stratford')
    GROUP BY T.TEAMNO, M.PLAYERNO
    HAVING COUNT(M.PLAYERNO) > 0

-- 2. Try to modify and delete some views that you create in point 1.
-- Modify view PLAYERS_WITHOUT_MATCHES
ALTER VIEW PLAYERS_WITHOUT_MATCHES
AS
    SELECT P.PLAYERNO, P.NAME
    FROM PLAYERS P
        LEFT OUTER JOIN MATCHES M ON P.PLAYERNO = M.PLAYERNO
    WHERE M.PLAYERNO IS NULL
    ORDER BY P.PLAYERNO

-- Delete view PLAYER_TOTAL_PENALTIES
DROP VIEW PLAYER_TOTAL_PENALTIES
